apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gd5go
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: gd5go

spec:
  # ingressClassName: gd5go
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gd5go
            port:
              number: 80
